### ISSUE TITLE
[React native] [Teams] Members counter is not updated when user joins/leaves team

### ISSUE THREAD

**Issue by Dasha1990** [letsdoitworld/World-Cleanup-Day#301] opened 2018-06-28 07:54 UTC
Device: Samsung S4 note 6.0.1, iPhone 6 11.4

**Steps to reproduce:**
1. login to the app
2. Join any team
3. Check response
http://52.143.138.160:50000/api/v1/me/team is sent 
with team id
 {
	"team": "3b61c81a-2b8e-11e8-b467-0ed5f89f718r"
}
and team entity in response is:
	"teamInfo": {
		"name": "GSMA",
		"teamDescription": "Are you an employee or friend of GSMA. Join this team and help to make the change towards a cleaner and healthier world.",
		"image": "https://ucarecdn.com/82023a51-d50a-4f2f-aa0f-7e3a938de06b/Blueish.png",
		"nationalTeam": true,
		"createdAt": "2018-06-27T13:38:11.882Z",
		"id": "3b61c81a-2b8e-11e8-b467-0ed5f89f718r",
		"members": 0,
		"trashpoints": 0,
		"lastTrashpoints": [],
		"groupCount": {}
	}

**Actual result:** team is returned in users profile as his team but member counter is not updated + trashpoints which user creats aren't added to team statistics + user can join any other team without leaving current one and teams are just overwritten in his profile http://take.ms/uu8zU

Expected result: user becomes team member and member counter increased by 1

**Comment by lynxlynxlynx** [comment] 2018-06-28 08:00
Partly a duplicate of https://github.com/letsdoitworld/World-Cleanup-Day/issues/287
it's unclear if the fixes were moved over, they don't seem to be merged to master yet.

**Comment by Dasha1990** [comment] 2018-06-28 08:02
got it. as I understand now this works fine on the prod so we would need to find and add this functionality to server side

**Comment by Dasha1990** [comment] 2018-06-28 08:05
now its blocking us from checking full flow, cause we can't correctly join team, see members list, see team stats

**Comment by lynxlynxlynx** [comment] 2018-06-28 08:16
Surely that's a different or higher level bug?

**Comment by Dasha1990** [comment] 2018-06-28 08:20
I guess this issue with join also caused all other stuff and server logic will work when users will join team correctly (as I understand it is only backend part and apps can't really affect it)

**Closed** 2018-07-03 14:54 UTC
