### ISSUE TITLE
[Web] [React native] [Android]  different results of trashpoint creator name

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#319] opened 2018-07-17 12:32 UTC
![not same logic for app and web app](https://user-images.githubusercontent.com/26063413/42817159-e6a6081c-89d5-11e8-8a18-018070f3e3ce.jpg)
I as super admin logged in to web app can't see who created trashpoint.
I opened the same trashpoint in mobile app and I saw creators name.

**Comment by KristiinaKerge** [comment] 2018-07-17 12:56
Chrome Version 67.0.3396.99
Sony Xperia F5321, Android 8.0.0

**Comment by KristiinaKerge** [comment] 2018-07-17 13:01
![private profile](https://user-images.githubusercontent.com/26063413/42818648-20fbba26-89da-11e8-85f9-ac15f1df5f1d.jpg)
user who created this trashpoint has private profile
logged in with google

**Comment by Dasha1990** [comment] 2018-07-17 13:16
Thank you for all the details! I checked app and web app behavior and it seems that currently same logic is used for mobile/web app. Can this issue be caused by changing user privacy after trashpoint details were received from the backend? 
Also Anastasia just corrected me and said that all admins should always see creator/updater name. So I guess this is an issue

**Comment by KristiinaKerge** [comment] 2018-07-17 13:19
she didn't change privacy just updated  the app

**Comment by KristiinaKerge** [comment] 2018-07-17 14:25
No it is anonymous in mobile app.

**Comment by KristiinaKerge** [comment] 2018-07-19 20:43
what is the status?

**Comment by Dasha1990** [comment] 2018-07-20 12:51
We are deploying fix if this case to the stage env

**Comment by lynxlynxlynx** [comment] 2018-07-27 15:36
From what I gather, this and #322 were the same bug report, so closing.

**Closed by lynxlynxlynx** 2018-07-27 15:36 UTC
Labels: bug
